<?
// example how to add css and js from template
$this->headLink()->appendStylesheet('/.VivoSampleModule.resource/css/smoothness/jquery-ui-1.9.2.custom.css');
$this->headLink()->appendStylesheet('/.VivoSampleModule.resource/css/ajax-loading.css');
$this->headScript()->appendFile('/.VivoSampleModule.resource/js/jquery-1.8.3.js');
$this->headScript()->appendFile('/.VivoSampleModule.resource/js/jquery-ui-1.9.2.custom.js');
$this->headScript()->appendFile('/.VivoSampleModule.resource/js/autocomplete.js');

$this->headScript()->appendFile('/.Vivo.resource/js/ajax-validation.js');
$this->headScript()->captureStart() ?>
setUpAjaxValidation({
    elementId:              'zip',
    valInfoId:              'validateZip\\[a\\]',
    url:                    '<?php echo $this->document($doc) ?>',
    applyStatusSelector:    '#validateZip\\[a\\]'
});

setUpAjaxValidation({
    elementId:              'customer\\[person\\]\\[last_name\\]',
    valInfoId:              'testLastName',
    url:                    '<?php echo $this->document($doc) ?>',
    applyStatusSelector:    '#cgroup-customer\\[person\\]\\[last_name\\]'
});

<?php $this->headScript()->captureEnd() ?>
<div class="samplediv">

<h3>Customer UI component</h3>

<?php
    /** @var $form \VivoSampleModule\Form\Customer */
    if ($form->getMessages()) {
        echo '<p>' . $this->escapeHtml($this->translate('Invalid input provided')) . '</p>';
    }
    //Add hidden field containing the required action
    $form->add(array(
        'name'          => 'act',
        'attributes'    => array(
            'type'          => 'hidden',
            'value'         => $this->action('submit'),
        ),
    ));

    $fsCustomer = $form->get('customer');
    $fsPerson   = $fsCustomer->get('person');
    $fsAddress  = $fsCustomer->get('address');
    echo $this->formTwb()->openTag($form);
?>

<div class="form_element"><?php echo $this->formRowTwb($fsPerson->get('first_name')); ?></div>
<div class="form_element"><?php echo $this->formRowTwb($fsPerson->get('last_name')); ?></div>
<div class="form_element"><?php echo $this->formRowTwb($fsPerson->get('degrees')); ?></div>
<div class="form_element"><?php echo $this->formRowTwb($fsAddress->get('street')); ?></div>
<div class="form_element"><?php echo $this->formRowTwb($fsAddress->get('town')); ?></div>
<div class="form_element ajax-val-info-zip"><?php echo $this->formRowTwb($fsAddress->get('zip')); ?></div>
    <span id="validateZip[a]" class="ajax-val-info-zip"></span>

<?php
    $dobContent = $this->formRowTwb($fsCustomer->get('dob'));
?>

<div class="form_element"><?php echo $dobContent; ?></div>

<div class="form_element"><?php echo $this->formRowTwb($form->get('act')); ?></div>
<div class="form_element"><?php echo $this->formRowTwb($form->get('submit')); ?></div>
<div class="form_element"><?php echo $this->formRowTwb($form->get('csrf')); ?></div>

<?php echo $this->formTwb()->closeTag(); ?>

</div>

<span id="testLastName"></span>